version: '3'

services: 
  apache_php: 
    build: ./httpd 
    ports: 
      - 8080:80 
    volumes: 
      - ./src:/var/www/html
    links: 
      - db 
    depends_on: 
      - db 
 
  db: 
    image: mariadb:10.3   
    volumes: 
      - ./mariadb:/var/lib/mysql 
    environment: 
      DB_HOST: localhost
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: WD03
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: WD03
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    depends_on:
      - db